apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-data-profiler
  labels:
    app: snowflake_data_profiler
spec:
  selector:
    matchLabels:
      app: snowflake-data-profiler
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snowflake-data-profiler
    spec:
      containers:
      - image: randypitcherii/snowflake_data_profiler:latest
        name: sdp-container
        resources:
          limits:
            cpu: 0.9
          requests:
            cpu: 0.45
        ports:
          - containerPort: 5000





